name: Deploy Master Dashboard

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Inject Configuration
        env:
          CONFIG_SECRET: ${{ secrets.FIREBASE_CONFIG_CONTENT }}
        run: |
          mkdir -p js
          echo "$CONFIG_SECRET" > js/config.js
          # Quitar la regla de ignore para que el archivo temporal se pueda subir a gh-pages
          sed -i '/js\/config\.js/d' .gitignore

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true
